const mongoose = require("mongoose");
const { validate_email, validate_number } = require("../middleware/validator");

const surveyee_schema = new mongoose.Schema({
	lastname: {
		type: String,
		trim: true,
		required: [true, "please provide a last name"],
	},
	firstname: {
		type: String,
		trim: true,
		required: [true, "please provide a first name"],
	},
	middlename: {
		type: String,
		trim: true,
		required: [true, "please provide a middle name"],
	},
	sex: {
		type: String,
		default: "male",
	},
	age: {
		type: Number,
		default: 12,
		min: 12,
		max: 99,
	},
	contact_number: {
		type: String,
		trim: true,
		validate: [validate_number, "please provide a valid number"],
		required: [true, "please provide your contact number"],
	},
	email: {
		type: String,
		trim: true,
		validate: [validate_email, "please provide a valid email"],
		required: [true, "please provide your email"],
	},
	address: {
		type: String,
		trim: true,
		required: [true, "please provide an address"],
	},
	college: {
		type: String,
		default: "College of Allied Medical Professions",
		enum: [
			"College of Allied Medical Professions",
			"College of Arts and Sciences",
			"College of Business and Accountancy",
			"College of Computer Studies",
			"College of Criminal Justice Education",
			"College of Engineering and Architecture",
			"College of Education",
			"College of Nursing",
			"School of Law",
			"School of Medicine",
			"Graduate School",
		],
	},
	course: {
		type: String,
		default: "Bachelor of Science in Clinical Pharmacy",
		enum: [
			"Bachelor of Science in Clinical Pharmacy",
			"Bachelor of Science in Medical Technology",
			"Bachelor of Science in Occupational Therapy",
			"Bachelor of Science in Pharmacy",
			"Bachelor of Science in Physical Therapy",
			"Bachelor of Science in Radiologic Technology",
			"Bachelor of Arts in Communication",
			"Bachelor of Arts in Psychology",
			"Bachelor of Arts in Psychology - Master of Arts in Psychology",
			"Bachelor of Science in Biology",
			"Bachelor of Science in Psychology",
			"Bachelor of Science in Accountancy",
			"Bachelor of Science in Business Administration",
			"Bachelor of Science in Hospitality Management",
			"Bachelor of Science in Hotel and Restaurant Management",
			"Bachelor of Science in Management Accounting",
			"Bachelor of Science in Tourism Management",
			"Bachelor of Multimedia Arts",
			"Bachelor of Science in Computer Science",
			"Bachelor of Science in Information Technology",
			"Bachelor of Science in Criminology",
			"Bachelor of Science in Architecture",
			"Bachelor of Science in Civil Engineering",
			"Bachelor of Science in Computer Engineering",
			"Bachelor of Science in Electronics Engineering",
			"Bachelor of Elementary Education",
			"Bachelor of Secondary Education",
			"Bachelor of Special Needs Education",
			"Bachelor of Science in Nursing",
			"Juris Doctor",
			"Doctor of Medicine",
			"Doctor in Business Administration (Professional Track)",
			"Doctor of Information Technology",
			"Doctor of Philosophy in Curriculum and Instruction",
			"Doctor of Philosophy in Education",
			"Doctor of Public Health in Health Promotion and Education",
			"Doctor of Public Health in Health Promotion and Education (Professional Track)",
			"Master in Business Administration",
			"Master in Information Technology",
			"Master in Nursing",
			"Master in Public Health",
			"Master of Arts in Education",
			"Master of Arts in Nursing",
			"Master of Arts in Psychology",
			"Master of Medical Laboratory Science",
			"Master of Science in Criminal Justice with Specialization in Criminology",
			"Master of Science in Medical Laboratory Science",
			"Master of Science in Physical Therapy",
			"Master of Science in Public Health",
			"",
		],
	},
	position: {
		type: String,
		default: "employee",
		enum: ["Employee", "Student"],
	},
});

module.exports = mongoose.model("Surveyee", surveyee_schema);
